obj-y += dc.o
obj-y += rgb.o
obj-$(CONFIG_TEGRA_HDMI) += hdmi.o
obj-$(CONFIG_TEGRA_HDMI) += nvhdcp.o
obj-y += edid.o
obj-y += lcd_edid.o
obj-$(CONFIG_TEGRA_DSI) += dsi.o
obj-$(CONFIG_TEGRA_OVERLAY) += overlay.o
